# Generated by Django 5.0.1 on 2024-03-09 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocery',
            old_name='pet_image',
            new_name='grocery_image',
        ),
    ]
