# Generated by Django 5.0.1 on 2024-03-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GroceryApp', '0003_grocery_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='discounted_percentage',
            field=models.IntegerField(default=1),
        ),
    ]
